### ISSUE TITLE
Replace Sensory wakeword engine in SDK

### ISSUE THREAD

**Issue by lucianomartin** [xmos/avs-device-sdk#70]
Sensory withdrew the public repo containing their proprietary wakeword engine in 2021. 

By default, the AVS Setup should not attempt to install Sensory.  However, it must still be possible to use Sensory which may be a requirement for AVS testing, but we must also support AVS using the integrated AMZ WW in 3615.

**Comment by andrewdewhurst** [comment]
**Outline plan**

- The AVS setup should NOT try to install Sensory; but
- there needs to be a documented/reliable way for someone with their own sensory license to install it and select it as the WW
- Our default needs to use the 3615 AMZ WW engine; which means
- that the RaPi setup should use an interrupt to trigger, and use the new "REWIND" mechanism in the client
- Assumption is that for AVS demo/eval we ONLY support the INT builds.

**Comment by lucianomartin** [comment]
@lucianomartin will check if the reference audio on a RPi can be routed to both the speakers and the XVF3610/3615.

**Comment by lucianomartin** [comment]
@andrewdewhurst @mbanth, I see only 2 tasks left for this issue:

 1.  replace Sensory with Amazon KWD
 2. check how to send reference audio to the speakers
Point 1. is already covered by https://github.com/xmos/vocalfusion-avs-setup/issues/62
For point 2. I thought it is enough to use the DAC of the voice reference board.

If you agree with my conclusions, I can set the story points to 3 to cover the efforts so far and set this issue as done. What do you think?
